# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94b54ad378342cc74469772cb63059ffa7634b69245c8f015974ae628313dfea0fc050b159738fc5084a15d1f936501bdbf32304b43d91452f600e8d062076b4

test:
  secret_key_base: 1da67b6a1dd0e6086efd30c93af27e62d8f6be20eee449f129ac239334bbf8cc0b58e943a814eccb2f725974d1fd23ea9fe5bae59e62b1a0d4565b11c11e84fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
